#Should force despawn of mobs like hyperevolved and calamities
"Despawn fix" = true
#This forces mobs to only spawn in specific dimensions. By default will try to only spawn Lost Cities dimension
"Nightmare Mod" = true
#List of dimensions that mobs are allowed to spawn, only usable if Nightmare mod is set true
"Allowed Dimensions" = ["minecraft:overworld"]
#This allows this mod to configure the amount of damage that can ignore reduction
"Control piercing" = true
#Control % damage bypass from the piercer variant from Slasher
#Range: 0.0 ~ 100.0
"Piercer Control" = 10.0
#Control % damage bypass from the Specter
#Range: 0.0 ~ 100.0
"Specter Control" = 10.0
#Control % damage bypass from the Ogre
#Range: 0.0 ~ 100.0
"Ogre Control" = 10.0
#Control % damage bypass from Calamities
#Range: 0.0 ~ 100.0
"Calamity Control" = 10.0

